#  reference: https://www.appveyor.com/docs/appveyor-yml/

# you can use {branch} name in version format too
# version: 1.0.{build}-{branch}

version: 1.1.0.{build}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true


# branches to build 
branches:
  # whitelist
  only:
    - master

#---------------------------------#
#    environment configuration    #
#---------------------------------#
    
image: Visual Studio 2019
clone_folder: c:\projects\nbxplorer

clone_depth: 1

configuration:
- Release

init:
- ps: dotnet --info

#---------------------------------#
#       build configuration       #
#---------------------------------#
before_build:

- ps: Write-Host "[$env:configuration] STARTED RabbitMq" -foregroundcolor "magenta"
- cmd: where docker
- cmd: docker version && docker-compose version
- cmd: docker-compose -f docker-compose.regtest.yml up -d rabbitmq

- ps: |
      Write-Host "[$env:configuration] STARTED dotnet restore" -foregroundcolor "magenta"
      
      dotnet restore -v m
      Write-Host "[$env:configuration] FINISHED dotnet restore" -foregroundcolor "magenta"
      if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }
    
build_script:
- ps: |
      Write-Host "[$env:configuration] STARTED dotnet build" -foregroundcolor "magenta"
      dotnet msbuild /p:Configuration=$env:configuration /p:Version=$env:APPVEYOR_BUILD_VERSION 
      Write-Host "[$env:configuration] FINISHED dotnet build" -foregroundcolor "magenta"
      if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode)  }
# scripts to run after build
after_build:
- ps: |
      if($env:configuration -eq 'Release')
      {
        Write-Host "[$env:configuration] STARTED dotnet pack" -foregroundcolor "magenta"
        
        cd NBXplorer.Client
        dotnet pack -c $env:configuration -v m --no-build -o $env:APPVEYOR_BUILD_FOLDER\nuget\      
        
        Write-Host "[$env:configuration] FINISHED dotnet pack" -foregroundcolor "magenta"
      }
      if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode)  }
    
test_script:
- ps: |
      Write-Host "[$env:configuration] STARTED dotnet test" -foregroundcolor "magenta"
      cd $env:APPVEYOR_BUILD_FOLDER
      dotnet test -c Release ./NBXplorer.Tests/NBXplorer.Tests.csproj --filter "Azure!=Azure" --logger:"console;noprogress=true"
      Write-Host "[$env:configuration] FINISHED dotnet test" -foregroundcolor "magenta"
      if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode)  }

     
#---------------------------------#
      
#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

# pushing all files in build directory recursively
artifacts:
- path: nuget\*.nupkg
  name: nuget packages
