FROM microsoft/dotnet:2.0.0-sdk as builder
WORKDIR /app
COPY . .
RUN cd NBXplorer && dotnet publish -c Release

FROM microsoft/aspnetcore:2.0.0
WORKDIR /app
COPY --from=builder "/app/NBXplorer/bin/Release/netcoreapp2.0/publish" .
ENTRYPOINT ["dotnet", "NBXplorer.dll"]