version: "3"
services:

  tests:
    build:
      context: ..
      dockerfile: NBXplorer.Tests/Dockerfile
      args:
        - SupportDBTrie=false
    environment:
          TESTS_POSTGRES: User ID=postgres;Include Error Detail=true;Host=postgres;Port=5432
    depends_on:
      - postgres
  # The dev container is not actually used, it is just handy to run `docker-compose up dev` to start all services
  dev:
    image: alpine:3.7
    command: [ "/bin/sh", "-c", "trap : TERM INT; while :; do echo Ready to code and debug like a rockstar!!!; sleep 2073600; done & wait" ]
    links:
      - postgres
      - pgadmin
  postgres:
    image:  postgres:13
    command: [ "-c", "random_page_cost=1.0", "-c", "shared_preload_libraries=pg_stat_statements" ]
    environment:
        POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "39383:5432"
    expose:
      - "5432"
  pgadmin:
    image: dpage/pgadmin4:6
    environment:
      PGADMIN_DEFAULT_EMAIL: "test@test.com"
      PGADMIN_DEFAULT_PASSWORD: "a"
    ports:
      - "8484:80"
    expose:
      - "5432"
    depends_on:
      - postgres
    volumes:
      - ./Docker/servers.json:/pgadmin4/servers.json
